### ISSUE TITLE
F-14 newly included commands in OB Patch 2.7.14.23966

### ISSUE THREAD

**Issue by danwatto** [Munkwolf/dcs-community-keybinds#20]
Hi,

Heatblur have added a bunch of commands and Axis that were previously only covered here.

This has resulted in duplicates when community keybinds are loaded. Possibly they have picked up your teams work and added it with the same names so they could now be removed from here.

I didn't get to checking/using the keys/buttons yet, but the input mapper highlighted these items in the AXIS section which I commented out:

F14 Pilot Axis - comment out axis that Heatblur added:
		--{cockpit_device_id = devices.HSD, action = device_commands.HSD_Knob_Brightness, name = _('HSD Brightness')},
		--{cockpit_device_id = devices.TACAN, action = device_commands.TACAN_Knob_Vol_Pilot, name = _('TACAN Volume')},
		--{cockpit_device_id = devices.ICS, action = device_commands.RADIO_ICS_Vol_ALR67_Pilot, name = _('ALR-67 Volume')},
		--{cockpit_device_id = devices.ICS, action = device_commands.RADIO_ICS_Vol_Sidewinder, name = _('Sidewinder Volume')},
		--{cockpit_device_id = devices.HUD, action = device_commands.VDIG_HUD_trim, name = _('HUD Trim')},
		--{cockpit_device_id = devices.VDI, action = device_commands.VDIG_VDI_contrast, name = _('VDI Screen Contrast')},
		--{cockpit_device_id = devices.HUD, action = device_commands.VDIG_HUD_bright, name = _('HUD Brightness')},

F14 Rio Axis - comment out axis that Heatblur added:
	--{cockpit_device_id = devices.TACAN, action = device_commands.TACAN_Knob_Vol_RIO, name = _('TACAN Volume')},

OB Patch 2.7.14.23966
https://www.digitalcombatsimulator.com/en/news/changelog/openbeta/

The relevant section:

Fixed INS mode switch bindings not being functional.
Fixed VHF/UHF ARC-182 Volume Pilot Inc/Dec keybindings.
Added “_(name)” for default.lua in mods/inputs.
Added new bindable inputs for the pilot:
Pilot Oxygen Toggle
Emergency Wing Sweep Handle Cover Toggle
Emergency Wing Sweep Handle Pull
Emergency Wing Sweep Handle Push
Emergency Wing Sweep Handle Pulled else Pushed
Emergency Wing Sweep Handle Pushed else Pulled
Emergency Wing Sweep Handle Pushed/ Pulled toggle
Eng/Probe Anti Ice Toggle
Asymmetric Thrust Limiter Cover Toggle
Asymmetric Thrust Limiter Toggle
Hydraulic Transfer Pump Switch Toggle
Hydraulic Transfer Pump Switch Cover Toggle
Fuel Feed Cover Toggle
Fuel Feed Toggle
VDI Screen Brightness Knob Inc
VDI Screen Brightness Knob Dec
VDI Screen Contrast Inc
VDI Screen Contrast Dec
VDI Trim Inc
VDI Trim Dec
HUD Brightness Knob Inc
HUD Brightness Knob Dec
HUD Trim Inc
HUD Trim Dec
HUD Filter Toggle
HUD Filter pulled else pushed
HSD Brightness Knob Inc
HSD Brightness Knob Dec
Antiskid & Spoiler BK - Toggle
Emergency Wing Sweep Handle move Fwd
Emergency Wing Sweep Handle move Aft
BINGO Fuel Level Knob Inc
BINGO Fuel Level Knob Dec
Radar Altimeter Control Knob +
Radar Altimeter Control Knob -
Radar Altimeter Test
Master Test Selector CW
Master Test Selector CCW
Master Test Selector: OFF
Master Test Selector: LTS
Master Test Selector: FIRE DET/EXT
Master Test Selector: INST
Master Test Selector: OBC
Master Test Selector: EMERG GEN
Master Test Selector: WG SWP
Master Test Selector: FLTGR DW
Master Test Selector: FLTGR UP
Master Test Selector: D/L RAD
Master Test Selector: STICK SW
Master Test Selector PULLED else PUSHED
Master Test Selector push/pull toggle
HSD Test Button
Added new bindable axes for the pilot:
HSD Brightness
HSD Selected Heading
HSD Selected Course
ICS Volume Pilot
Sidewinder Volume
ALR-67 Volume
VHF/UHF ARC-182 Volume Pilot
HUD Brightness
HUD Trim
VDI Screen Brightness
VDI Screen Contrast
VDI Trim
TACAN Volume
Maneuver flaps (unrealistic but wanted by some)
Emergency Wing Sweep
Added new bindable inputs for the RIO:
ATTK mode CW
ATTK mode CCW
Elec Fuse CW
Elec Fuse CCW
Elec Fuse: Safe
Elec Fuse: VT
Elec Fuse: INST
Elec Fuse: DLY1
Elec Fuse: DLY2
Missile Speed Gate CW
Missile Speed Gate CCW
TID Mode CW
TID Mode CCW
TID range +
TID range -
Added new bindable axes for the RIO:
ICS Volume RIO
AN/ALR-67 Volume
VHF/UHF ARC-182 Volume RIO
TACAN Volume

**Comment by Munkwolf** [comment]
Thanks for the write-up. I've been meaning to start a new round of updates to get things current with the latest open beta changes. Will start that today with the F-14.

**Comment by Munkwolf** [comment]
Published a new release with updates for the F-14. Let me know if I missed anything.

**Comment by danwatto** [comment]
Great thanks

**Comment by danwatto** [comment]
> Published a new release with updates for the F-14. Let me know if I missed anything.

I've been mapping the RIO and noticed they didn't include a way to close the AI menu. You can close it with the Toggle command but that requires you to move your head to put the cursor in the center first. Copying the Jester close command works. 

You may add this to the RIO list of commands:
{cockpit_device_id=devices.JESTERAI, down=device_commands.JESTER_CloseMenu, value_down=1.0,  name=_('Close Menu'),	 category=_('Iceman AI')},

I'm sure there's more but I haven't really learnt the RIO yet, just mapping the basics.

Unfortunately Heatblur is really spartan on the RIO bindings, there's alot of things missing. 
The Weapon Type wheel I'd love to bind to my controls too but I can't find anything making it available. 
Since they've added some bindings in the last update I hope there are more to come.

**Comment by danwatto** [comment]
edited above comment with a few more commands

**Comment by Munkwolf** [comment]
The above updates are now added to the codebase. They will be part of next release. Not sure if it was a recent update, but weapon type wheel bindings are available? Then an axis version for the wheel is part of the keybinds here.

**Comment by danwatto** [comment]
Thanks great.
Yes I noticed the weapon type wheel, and mapped it.
Cheers
