### ISSUE TITLE
F14 RIO OB patch 2.7.15.26783

### ISSUE THREAD

**Issue by danwatto** [Munkwolf/dcs-community-keybinds#22]
Some new AXIS commands added in the patch for the F14 RIO.

These are no longer needed and show as duplicates in the axis section for the RIO:

DDD Brightness
DDD Pulse Video
TID Brightness
TID Contrast

**Comment by Munkwolf** [comment]
Thanks for the heads up, it should be fixed this week.

**Comment by Munkwolf** [comment]
These have been removed in the 22.7.6 release.
