### ISSUE TITLE
P51/TF51 Missing value_up field for 'Landing Gear Down else Up' and 'Landing Gear Up else Down' commands

### ISSUE THREAD

**Issue by correca** [Munkwolf/dcs-community-keybinds#23]
There are actually two 'value_down' fields. One of them, the last one, should be 'value_up' to fix it.

Thank you very much for your work.

**Comment by Munkwolf** [comment]
Hey, thanks for the heads up. It should be fixed sometime this week.

**Comment by Munkwolf** [comment]
This should be fixed in the 22.7.6 release.
