### ISSUE TITLE
C-101EB / C-101CC :  device_commands.Button_118 should be device_commands.Button_430 

### ISSUE THREAD

**Issue by correca** [Munkwolf/dcs-community-keybinds#24]
'-- Throttle' section, all Rear Cockpit  'Throttle Idle Detent' commands are using the wrong device_commands.Button_118

Affected lines 426 to 429: replace Button_118 with Button_430

https://github.com/Munkwolf/dcs-community-keybinds/blob/7ec928f355fa338263b479cef497ef3bb8a4a59c/InputCommands/C-101/Input/C-101CC/joystick/default.lua#L426

**Comment by Munkwolf** [comment]
Thanks for reporting, should be fixed in new 22.7.7 release. Also added the air brake command you mentioned in discussions.

**Comment by correca** [comment]
Nice. With those corrections 'Throttle Idle Detent' will be functional for front cockpit. Thanks mate!
