### ISSUE TITLE
UH-1H:  Wrong value_up for 'Landing Light Switch..(2-way Switch)' keybinds

### ISSUE THREAD

**Issue by correca** [Munkwolf/dcs-community-keybinds#30]
Hi, in order to work fine I changed value_up value for those '2-way Switch' keybinds

		-- Collective

		{down = device_commands.Button_7, up = device_commands.Button_7, cockpit_device_id = devices.NAVLIGHT_SYSTEM, value_down = 1, value_up = -1, name = _('Landing Light Control Switch Extend else Off (2-way Switch)'), category = {_('Ins Collective Stick'), _('Custom')}},
		{down = device_commands.Button_7, up = device_commands.Button_7, cockpit_device_id = devices.NAVLIGHT_SYSTEM, value_down = -1, value_up = 1, name = _('Landing Light Control Switch Retract else Off (2-way Switch)'), category = {_('Ins Collective Stick'), _('Custom')}},

**Comment by correca** [comment]
I am closing the issue because I just realized that you are already working on this issue. Thank you for everything.

**Comment by correca** [comment]
Sorry, this issue is still open

**Comment by Munkwolf** [comment]
I added the search light commands in a recent commit, and the above landing light commands as an alternate. They'll be a part of the next release after I work through some other updates.

The landing light is a 3-way switch, and the commands I originally added work as a 3-way, with the up actions returning the switch to the off position. I added your commands above as an alternate, as retract-else-extend and extend-else-retract, since they don't return the switch to the off position.

**Comment by correca** [comment]
I think it is perfect to have both options. Many of the command pairs I propose are intended to be used in conjunction with the 3-position switches. I recently got a Warthog and am trying to take advantage of the throttle control switches.


De: ***@***.***>
Enviado: sábado, 16 de julio de 2022 17:18
Para: ***@***.***>
CC: ***@***.***>; State ***@***.***>
Asunto: Re: [Munkwolf/dcs-community-keybinds] UH-1H: Wrong value_up for 'Landing Light Switch..(2-way Switch)' keybinds (Issue #30)


I added the search light commands in a recent commit, and the above landing light commands as an alternate. They'll be a part of the next release after I work through some other updates.

The landing light is a 3-way switch, and the commands I originally added work as a 3-way, with the up actions returning the switch to the off position. I added your commands above as an alternate, as retract-else-extend and extend-else-retract, since they don't return the switch to the off position.
