### ISSUE TITLE
BF-109K-4: Custom keybind commands for Governor Automation are reversed

### ISSUE THREAD

**Issue by correca** [Munkwolf/dcs-community-keybinds#37]
These commands act contrary to their description:

		-- Engine Controls

		{cockpit_device_id = devices.FUSEBOX, down = device_commands.Button_58, up = device_commands.Button_58, value_down = 1, value_up = 0, name = _('Governor Automation OFF else ON (2-way Switch)'), category = {_('Engine Controls'), _('Custom')}},
		{cockpit_device_id = devices.FUSEBOX, down = device_commands.Button_58, up = device_commands.Button_58, value_down = 0, value_up = 1, name = _('Governor Automation ON else OFF (2-way Switch)'), category = {_('Engine Controls'), _('Custom')}},

Solution: Swap descriptions between both

**Comment by Munkwolf** [comment]
Hey, sorry it's taken so long for me to respond! Thanks for the heads up, I'll get this fixed up soon.

**Comment by Munkwolf** [comment]
This should now be fixed.
