### ISSUE TITLE
Possible to include a Landing Gear Down Else Up for the A10C/C2?

### ISSUE THREAD

**Issue by Bumblefox** [Munkwolf/dcs-community-keybinds#42]
Surprised I did not see a "Landing gear down, else up" option for the A10C/A10C2? Is it possible to add this one or is there a limitation on those modules.

**Comment by Munkwolf** [comment]
Hey! Sorry it's taken so long for me to respond. It should be possible. I'll have more free time available soon to do some updates and will take a look.

**Comment by Bumblefox** [comment]
no worries, man. I've been trying to piece it together myself and... not quite figuring it out XD

**Comment by correca** [comment]
In case it helps. I have tested these commands for both the A10C and the A10C II and they work correctly:

`
{cockpit_device_id = devices.CPT_MECH, down = device_commands.Button_1, up = device_commands.Button_1, value_down = 1, value_up = -1, name = _('Landing Gear UP else DOWN (2-way Switch)'), category = {_('Custom'), _('Landing gear panel')}},

{cockpit_device_id = devices.CPT_MECH, down = device_commands.Button_1, up = device_commands.Button_1, value_down = -1, value_up = 1, name = _('Landing Gear DOWN else UP (2-way Switch)'), category = {_('Custom'), _('Landing gear panel')}},
`

**Comment by Bumblefox** [comment]
Rock on, man. I'll give those a try. and see if I can't wrap my head around the syntax ;3

Thank you!

**Comment by Bumblefox** [comment]
Request resolved.
