### ISSUE TITLE
A10C_2 Canopy open doesn't work

### ISSUE THREAD

**Issue by OloRatuj** [Munkwolf/dcs-community-keybinds#44]
https://github.com/Munkwolf/dcs-community-keybinds/blob/074eadb4111d5bb376102aeb365aa8b3d6854955/InputCommands/A-10C_2/Input/A-10C_2/joystick/default.lua#L137

Something is wrong and the open canopy binding for A10C_2 doesn't work. Are value_down=1 and cocpit_device_id=39 ok?

**Comment by danw-eth** [comment]
I added this to mine:

--Fix the canopy, broken in ED patch
		{down = 3007, cockpit_device_id = devices.CPT_MECH, value_down = 1.0,	name = _('Canopy OPEN ALL THE WAY TAIPAN'), category = 'Special'},
		{down = 3007, up = 3007, cockpit_device_id = 39, value_down = 1.0, value_up = 0.0, name = _('Canopy OPEN else HOLD TAIPAN'), category = 'Special'},
		{down = 3006, up = 3007,cockpit_device_id = devices.CPT_MECH, value_down = 0.0,	value_up = 0.0, name = _('Canopy CLOSE else HOLD TAIPAN'), category = 'Special'},

**Comment by OloRatuj** [comment]
Thanks @danw-eth . I have created merge request to add this solution to main branch.

**Comment by Munkwolf** [comment]
This has been merged and updated a bit. Apologies for the delay in getting around to it.
