### ISSUE TITLE
AH-64 Apache CPG Left Handgrip FLIR/TV/DVO three-way keybind bug

### ISSUE THREAD

**Issue by SaiRacing** [Munkwolf/dcs-community-keybinds#47]
Hi, the configuration for the mentioned three-way keybind does not give the intended outputs. Looking at the original default.lua in the DCS root folder I found that the down and up arguments were incorrect. Here are the tested correct keybinds:

`{cockpit_device_id = devices.TEDAC_INPUT, down = tedac_commands.LHG_TADS_SENSOR_SELECT_SW_FLIR, up = tedac_commands.LHG_TADS_SENSOR_SELECT_SW_TV, value_down = 1, value_up = 0, name = _('LHG TADS Sensor Select Switch - FLIR else TV (3-way Switch Down)'), category = {_('TEDAC'), _('Left Handgrip'), _('Custom')}},
		{cockpit_device_id = devices.TEDAC_INPUT, down = tedac_commands.LHG_TADS_SENSOR_SELECT_SW_DVO, up = tedac_commands.LHG_TADS_SENSOR_SELECT_SW_TV, value_down = -1, value_up = 0, name = _('LHG TADS Sensor Select Switch - DVO else TV (3-way Switch Up)'), category = {_('TEDAC'), _('Left Handgrip'), _('Custom')}},`

Unfortunately I don't know how to use git to add this fix to the project, so this is the next best way I figured.

**Comment by Munkwolf** [comment]
Thank you, these changes are now committed.
