### ISSUE TITLE
X56 mini stick on Joystick

### ISSUE THREAD

**Issue by H1ghSp4rr0w** [Munkwolf/dcs-community-keybinds#50]
Hello,
Thank you for all the great work you put in!
Do you know a way to make the mini stick on the X56 Joystick to 4 buttons or a hat via LUA? Not via logitechs horrible software.

**Comment by Munkwolf** [comment]
For that I would recommend Joystick Gremlin: http://whitemagic.github.io/JoystickGremlin/

You can use gremlin to have an axis send button presses to a virtual joystick at a specific range. Then you'd map the virtual joystick buttons in game.

Trying to do it via LUA files would likely mean having to do different things per module to get it working, and it might not always work. Gremlin should always work, and not be tied to the LUA of any one module.

I use gremlin to do axis-to-button for the slider on my warthog throttle, to have 5 different buttons across the range of the slider. For your X56 mini stick, you could setup buttons for each axis of it to send button presses when it's pushed left/right/up/down.

In gremlin, you'd want to add a Remap action to the axis of your mini-stick, and then select what button it should trigger on your vjoy device. Then there is a tab on the side of the Remap action named Virtual Button, in there you can set what range of the axis that button should be active for. You can add extra Remap actions, like if you wanted an extra button to activate when you move the mini stick all the way to one side (ex: one button active for axis is between 0.1 - 1, then another button active when axis is between .8 - 1).

**Comment by H1ghSp4rr0w** [comment]
Wow thank you so much!! Will test it right away!
