### ISSUE TITLE
FC3 F15 Digital TDC slew axis

### ISSUE THREAD

**Issue by downloadpizza** [Munkwolf/dcs-community-keybinds#52]
First of all thank you for the amazing work.
Now im not sure if this is possible, but:
The TDC slew axis (radar target selector thingy) can only be bound to analog axis, which is troublesome for people who want to bind it to a digital 4 way HAT.
Would it be possible to add "TDC up", "TDC down", "TDC left" and "TDC right"? I understand that the sensitivity would be hardcoded, but people can just edit it if they want it slower or faster. If this is not possible due to DCS limitations then sad, but cant do anything about it.

**Comment by Munkwolf** [comment]
Hey, thanks for the kind words. That sounds like it should be possible. If it is, I should also be able to include a few different sensitivities like I do for similar commands in other modules (Very Slow, Slow, Fast, Very Fast, etc). I'll check into it this weekend.

**Comment by downloadpizza** [comment]
Oh yeah this seems like it extends to all of the FC3 planes

**Comment by downloadpizza** [comment]
Oh my bad its called "Target designator", at least in the Mig29. Disregard. Its just called differently in axis and buttons
