### ISSUE TITLE
Mirage F1 - common items are not injecting

### ISSUE THREAD

**Issue by danw-eth** [Munkwolf/dcs-community-keybinds#56]
All the items under InputCommands\Mirage-F1\Input\Common are not appearing in DCS input config.

Eg this is the axis list when running the default community keybinds with the latest version of Quaggles input command injector:

![image](https://github.com/Munkwolf/dcs-community-keybinds/assets/12576248/4425e109-8f75-4908-ba17-942c79ecdbfa)

The items in the specific "Mirage-F1EE" input file do get injected though, so I don't think there's a typo or anything. It seems it's just the folder structure?

Maybe the Mirage has changed something in a patch? I never tried it until now so I can't say how it was before. But in the main DCS folder, the structure is flat without a common section of binds.

**Comment by Munkwolf** [comment]
Thanks for the heads up! I will take a look sometime this week. I'm really close to finishing up some simpit upgrades that have taken longer than expected and kept me away from doing any updates with the keybinds project.

**Comment by danw-eth** [comment]
thanks, yeah I know the feeling! Switched to some winwing stuff and redoing binds is taking forever across so many modules. 

In the meantime I'm merging these into flat versions for the EE and CE which should work fine.

Thanks

**Comment by Munkwolf** [comment]
sorry for the delay! this should be fixed now in the release just published. the common files were renamed/moved.
