### ISSUE TITLE
Feature Request F/A-18 Radar Elevation Axis Keybind for use with rotary axis

### ISSUE THREAD

**Issue by Teclizitus** [Munkwolf/dcs-community-keybinds#58]
The current axis command does only work with a momentary axis - like an analogstick.
Would it be possible to add such a keybind?
Thank you

**Comment by Munkwolf** [comment]
Hi! Unfortunately that does not seem to be possible at the moment. There are three commands available for the radar elevation (up, down, axis), but they are all relative commands designed for momentary pushes.

**Comment by Teclizitus** [comment]
Ah, that's a shame. Thanks for checking though.
